### ISSUE TITLE
Surround

### ISSUE THREAD

**Issue by wanghankun** [axelfahy/jupyterlab-vim#11]
Can you please add features from surround? It's really something I can't live without.

**Comment by axelfahy** [comment]
I am not using it, so I don't plan on adding those features. 
Since this is not an official Vim feature, I think it should be implemented in another package. 
By the way, `vi(`, `vi'`, `vi"`, ... is working to select text within `(`, `'`, `"`, ...

**Comment by wanghankun** [comment]
Thank you
