### ISSUE TITLE
Not working on JupyterLab 2.1.5

### ISSUE THREAD

**Issue by osdf** [axelfahy/jupyterlab-vim#12]
Hi,
I updated to JupyterLab 2.1.5 (from 2.1.1), and now it seems that this extension no longer works.
Any idea of what I may do wrong?

Thanks!

**Comment by osdf** [comment]
Resolved: The issue was that I uninstalled and reinstalled the extensions using the extension manager. This leads to the problem described in https://github.com/jupyterlab/jupyterlab/issues/8122, with the solution at the end: delete `<conda_root>/share/jupyter/lab/settings/build_config.json`.

**Comment by StanczakDominik** [comment]
I can confirm that this fixes my issues as well!
