### ISSUE TITLE
Jupyterlab 3

### ISSUE THREAD

**Issue by quantum-booty** [axelfahy/jupyterlab-vim#14]
Is there any plan to port this to the newly released Jupyterlab 3? Thank you!

**Comment by axelfahy** [comment]
There is a Jupyterlab 3 version? The last version I have is jupyterlab==2.2.8 and the plugin is running on this version.
I think there are some works in progress to integrate the vim support directly inside jupyterlab (https://github.com/jupyterlab/jupyterlab/pull/8706). If this is not already the case with the next version, I will port it.

**Comment by quantum-booty** [comment]
Thank you, the latest commit is a pre-alpha version of 3.0
It would amazing to have it integrated inside Jupyterlab :)

**Comment by lukashergt** [comment]
> I think there are some works in progress to integrate the vim support directly inside jupyterlab (jupyterlab/jupyterlab#8706). If this is not already the case with the next version, I will port it.

Note that that PR got rebased and continued a few days ago in jupyterlab/jupyterlab#9068.

**Comment by ianhi** [comment]
Hiya, indeed it is now rebased and fully working + being reviewed. It stalled out for a while as the settings system was broken on jlab master which prevented working on it. I think an unfortunate consequence of this delay is that it may not land in version 3.0 as I expect they will not want to add new features at this point for fear of introducing bugs (but I could be wrong!). So we'll see what happens

**Comment by ianhi** [comment]
Hope springs eternal! From https://github.com/jupyterlab/jupyterlab/pull/9068#issuecomment-703052349

> There is a slot to get this merged in 3.0. We have discussed a bit about this during our last weekly meeting

Plus I think the final release of 3.0 has been pushed back. So fingers cross all goes well

**Comment by ianhi** [comment]
Hiya,

Sorry for the long hiatus  - I've been meaning to update this but life keeps getting in the way. 

So I went to a few of the jlab dev meetings to discuss this and the conclusion was that integrating the vim keymap for the notebook is too big of a change to make for 3.0. However, there was general agreement that the current situation where `keymap` menu item only changes the file editor is a bad thing. So the plan is to work on including the notebook keymap in 3.1. Which is to say: The extension will need to be updated for 3.0 but as of 3.1 vim will likely be included in core.

As for updating:
With jlab3 there will be a new extension system ("federated extensions") that are distributed via pip and do **not** require a `jupyter lab build` step for end users. However, the old system (currently used by this extension) will continue to work fine. 

So I guess it's up to @axelfahy whether to update to the new system (requires creating a package on pypi) or to continue with `labextesion install` and npm packages.

If we do go for the pip distribution then the one substantive change is that the extension needs to call `ensureVimKeymap` which I added in https://github.com/jupyterlab/jupyterlab/pull/9161 to make sure that the jlab codemirror vim is loaded - webpack does some funky stuff I don't understand and imports from extensions will no longer affect jlab core in the same way - hence the new way of ensuring the vim keymap is loaded. You can see an example of this in jupyterlab-vimrc
https://github.com/ianhi/jupyterlab-vimrc/blob/6bb6e7cd0b5001009037ffbb728a153491d2196c/src/index.ts#L19-L25

**Comment by ianhi** [comment]
The other relevant open PR targeted at 3.1 is https://github.com/jupyterlab/jupyterlab/pull/9142 which creates a way to track cell creation rather than when the active cell changes which would be nice for this extension

**Comment by ianhi** [comment]
PR upgrading this extension to work with jlab3 and be pip installable (no build step) is here: https://github.com/axelfahy/jupyterlab-vim/pull/19
