### ISSUE TITLE
Update plugin to work with JupyterLab 3.0

### ISSUE THREAD

**Issue by zaneselvans** [axelfahy/jupyterlab-vim#22]
Apparently **[JupyterLab 3.0 has finally shipped](https://pypi.org/project/jupyterlab/3.0.0/)**! However, the dependencies listed on this plugin prohibit it from being installed, and the extension management system has (again) changed substantially. Hopefully it's not too hard!

**Comment by ianhi** [comment]
Hi @zaneselvans theres a PR for this here: https://github.com/axelfahy/jupyterlab-vim/pull/19

and while the PR hasn't been merged you can already use this extension with jlab3:

```
pip install jupyterlab_vim
```
```

**Comment by ianhi** [comment]
You may also be interested in some of the discussion re: a potential move into core jlab that is contained in https://github.com/axelfahy/jupyterlab-vim/issues/14

**Comment by zaneselvans** [comment]
Ah, great sorry! I searched the issues but not the PRs.

**Comment by axelfahy** [comment]
The PR has been merged, closing.
