### ISSUE TITLE
Allow enable/disable via settings?

### ISSUE THREAD

**Issue by asford** [axelfahy/jupyterlab-vim#24]
This appears to be the de-facto extension for jupyterlab 3.0, at least until https://github.com/jupyterlab/jupyterlab/pull/9068 lands. Would you be open adding settings-support in repo, so that this end-users can (at least) enable/disable the extension?

I would be happy to implement as a PR if you're open.

Work items:

- [ ] Add settings support via https://github.com/jupyterlab/extension-examples/tree/master/settings. 
- [ ] Add enable/disable flag under settings. Ie. https://github.com/jwkvam/jupyterlab-vim/pull/112
- [ ] Update esc behavior under settings. Ie. https://github.com/ryantam626/jupyterlab-vim/commit/0fd95cf3a3d821f26d438edfcb6a5ec1ae6783e1 and https://github.com/asford/jupyterlab-vim/commit/e02fd37fdbbcb751f381489e37de35f1a500703b

**Comment by axelfahy** [comment]
Sure, you can implement those features if you want. However, it might be duplicated work if the extension lands directly with jupyterlab.

**Comment by ianhi** [comment]
I haven't had time to work on moving it into jlab and unfortunately may not for a while yet. So 
1. If anyone wants to push that work on jlab forward they should feel free to (also welcome to ping me for reviews)
2. A short term fix for this would make sense
3. What should probably happen is that [jupyterlab-vimrc](https://github.com/ianhi/jupyterlab-vimrc) should be folded into this repo.

**Comment by mlucool** [comment]
This has been implemented in https://github.com/axelfahy/jupyterlab-vim/pull/32

**Comment by dclong** [comment]
I thought users can use `jupyter server extension enable/disable` to enable/disable an extension? However, it seems that the command doesn't work with jupyterlab-vim.

**Comment by dclong** [comment]
Is there a way to disable jupyterlab-vim for all users? I want to install the extension but keep it disabled by default since not all users are familiar with vim keybindings.

**Comment by dclong** [comment]
Never mind. I figured out that the right command to use is `jupyter labextension disable @axlair/jupyterlab_vim`.
