### ISSUE TITLE
New update note working anymore?

### ISSUE THREAD

**Issue by davibarreira** [axelfahy/jupyterlab-vim#25]
I've updated the package, and it's suddenly not working on JupyterLab 3 anymore. Any ideas why? I mean, Vim mode is just not present anymore.

**Comment by axelfahy** [comment]
How did you install the package? You may need to start from a new environment.

**Comment by davibarreira** [comment]
I used the Extensions Manager from Jupyter-Lab. I've tried reinstalling Jupyterlab, and restarting it

**Comment by axelfahy** [comment]
It is working on my site starting from a new environment, either with the Extensions Manager or with pip (`pip install jupyterlab-vim`). 
Have you tried creating a new environment?

**Comment by davibarreira** [comment]
Yeah... Well, then it's probably something on my system. Thanks for the answers. I'll try to uninstall (purge) and start again.

**Comment by davibarreira** [comment]
Uninstall conda and install everything. Now it works... Sorry for opening the issue and thanks for the help!
