### ISSUE TITLE
pypi upload failing

### ISSUE THREAD

**Issue by ianhi** [axelfahy/jupyterlab-vim#30]
@axelfahy Looks like the build worked but the upload failed:

![image](https://user-images.githubusercontent.com/10111092/109532358-09e35880-7a87-11eb-92eb-b8ddde18dc6a.png)

**Comment by ianhi** [comment]
I guess that pypi is down for uploads right now? This is probably a one time thing so once pypi get's fixed we should manually upload the package to both npm and pypi

**Comment by axelfahy** [comment]
Yes, I have the same error manually...

**Comment by axelfahy** [comment]
It was indeed an issue with PyPi servers. I have uploaded on PyPi and NPM, let's hope it uploads automatically next time. 
Thank you for the help!
