### ISSUE TITLE
Does not work in archlinux

### ISSUE THREAD

**Issue by Edenharder** [axelfahy/jupyterlab-vim#33]
My OS is Archlinux, I have installed Jupyterlab from Archlinux community.

My problem is that, any keystrokes except the arrows do not work if the plugin `axelfahy/jupyterlab-vim` is on.

I have thought that it was a problem of the browser firefox, then I tested chromium, same problem was still there.

What kind of further information do I need to provide?

**Comment by ianhi** [comment]
Do the bindings work correctly for you on https://codemirror.net/demo/vim.html ?

**Comment by Edenharder** [comment]
> Do the bindings work correctly for you on https://codemirror.net/demo/vim.html ?

You got it. The keybindings do not work either on that webpage!

**Comment by Edenharder** [comment]
After deleting some packages and updated the system, the keybindings works on that webpage now. But this extension still does not work for me. The new problem is that it is always in the insert mode.

**Comment by Edenharder** [comment]
Finally, I find out the reason. It's a problem with my input method. Everything works fine if I just switch to the normal input method.
