### ISSUE TITLE
Execuse me, could you please tell me how to build this project?

### ISSUE THREAD

**Issue by ysl2** [axelfahy/jupyterlab-vim#41]
I tried too many times but it still gave me errors.

I just want to modify the source code to map `<C-c>` to `<ESC>`. It's too hard for me to build the project. Please help.

**Comment by ianhi** [comment]
> I just want to modify the source code to map <C-c> to <ESC>. It's too hard for me to build the project. Please help.

This really ought to be configurable in the settings file that we now have. 


@ysl2 how far can you get through: https://github.com/axelfahy/jupyterlab-vim#development-install before things stop working? Can you post the errors you are having?

**Comment by ysl2** [comment]
OK, thanks for your help :-)
