### ISSUE TITLE
Escape out of edit mode

### ISSUE THREAD

**Issue by mlucool** [axelfahy/jupyterlab-vim#42]
Hi,

Without vim enabled, you can push escape to get out of cell edit mode (as shown below);
![leaveEditMode](https://user-images.githubusercontent.com/1813603/128758674-8051f9a6-600f-496d-a6f7-ca066023d4d8.gif)

Is there a hotkey already to do this? If not, can we add one?

**Comment by ianhi** [comment]
You want `Shift+Esc` which is added by this extension. You can also define your own shortcut using the jlab shortcut settings as this is just using a builtin jlab command `notebook:enter-command-mode`

https://github.com/axelfahy/jupyterlab-vim/blob/bbb7569c465e3b635f08fb4df12e05de350364dc/src/index.ts#L538-L542

**Comment by mlucool** [comment]
Ah thanks!
